// src/lib/cachedEnrichmentData.ts
//
// AUTO-GENERATED by scripts/refresh-enrichment.mjs
// Last generated: 2026-03-12T13:19:22.499Z
// Do not edit manually.

import type { RoleEnrichment, MarketEnrichment } from "./enrichmentData";

export const ENRICHMENT_CACHE_TIMESTAMP = "2026-03-12T13:19:22.499Z";

export const CACHED_ROLE_ENRICHMENTS: Record<string, RoleEnrichment> = {
  "creative-director": {
    "slug": "creative-director",
    "acs": null,
    "nea": {
      "blsCount": 97600,
      "moonlightingCount": 165000,
      "trueSupplyCount": 262600,
      "supplyMultiplier": 2.69,
      "moonlightingSharePct": 62.8,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 78,
          "freelancePct": 22
        },
        {
          "year": 2019,
          "staffPct": 76,
          "freelancePct": 24
        },
        {
          "year": 2020,
          "staffPct": 71,
          "freelancePct": 29
        },
        {
          "year": 2021,
          "staffPct": 68,
          "freelancePct": 32
        },
        {
          "year": 2022,
          "staffPct": 66,
          "freelancePct": 34
        },
        {
          "year": 2023,
          "staffPct": 63,
          "freelancePct": 37
        },
        {
          "year": 2024,
          "staffPct": 61,
          "freelancePct": 39
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 61,
        "freelancePct": 39
      },
      "wageGap": {
        "staffMedianUSD": 135000,
        "freelanceMedianUSD": 98000,
        "gapPct": 27.4
      },
      "reportYear": 2024
    }
  },
  "design-director": {
    "slug": "design-director",
    "acs": null,
    "nea": {
      "blsCount": 42300,
      "moonlightingCount": 71900,
      "trueSupplyCount": 114200,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 62.9,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 82,
          "freelancePct": 18
        },
        {
          "year": 2019,
          "staffPct": 80,
          "freelancePct": 20
        },
        {
          "year": 2020,
          "staffPct": 76,
          "freelancePct": 24
        },
        {
          "year": 2021,
          "staffPct": 73,
          "freelancePct": 27
        },
        {
          "year": 2022,
          "staffPct": 71,
          "freelancePct": 29
        },
        {
          "year": 2023,
          "staffPct": 68,
          "freelancePct": 32
        },
        {
          "year": 2024,
          "staffPct": 66,
          "freelancePct": 34
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 66,
        "freelancePct": 34
      },
      "wageGap": {
        "staffMedianUSD": 142000,
        "freelanceMedianUSD": 105000,
        "gapPct": 26.1
      },
      "reportYear": 2024
    }
  },
  "head-of-design": {
    "slug": "head-of-design",
    "acs": null,
    "nea": {
      "blsCount": 28100,
      "moonlightingCount": 47700,
      "trueSupplyCount": 75800,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 62.9,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 88,
          "freelancePct": 12
        },
        {
          "year": 2019,
          "staffPct": 87,
          "freelancePct": 13
        },
        {
          "year": 2020,
          "staffPct": 84,
          "freelancePct": 16
        },
        {
          "year": 2021,
          "staffPct": 82,
          "freelancePct": 18
        },
        {
          "year": 2022,
          "staffPct": 80,
          "freelancePct": 20
        },
        {
          "year": 2023,
          "staffPct": 78,
          "freelancePct": 22
        },
        {
          "year": 2024,
          "staffPct": 76,
          "freelancePct": 24
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 76,
        "freelancePct": 24
      },
      "wageGap": {
        "staffMedianUSD": 168000,
        "freelanceMedianUSD": 130000,
        "gapPct": 22.6
      },
      "reportYear": 2024
    }
  },
  "vp-of-design": {
    "slug": "vp-of-design",
    "acs": null,
    "nea": {
      "blsCount": 15400,
      "moonlightingCount": 26200,
      "trueSupplyCount": 41600,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 92,
          "freelancePct": 8
        },
        {
          "year": 2019,
          "staffPct": 91,
          "freelancePct": 9
        },
        {
          "year": 2020,
          "staffPct": 89,
          "freelancePct": 11
        },
        {
          "year": 2021,
          "staffPct": 87,
          "freelancePct": 13
        },
        {
          "year": 2022,
          "staffPct": 86,
          "freelancePct": 14
        },
        {
          "year": 2023,
          "staffPct": 84,
          "freelancePct": 16
        },
        {
          "year": 2024,
          "staffPct": 83,
          "freelancePct": 17
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 83,
        "freelancePct": 17
      },
      "wageGap": {
        "staffMedianUSD": 195000,
        "freelanceMedianUSD": 160000,
        "gapPct": 17.9
      },
      "reportYear": 2024
    }
  },
  "cco": {
    "slug": "cco",
    "acs": null,
    "nea": {
      "blsCount": 8200,
      "moonlightingCount": 13900,
      "trueSupplyCount": 22100,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 62.9,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 94,
          "freelancePct": 6
        },
        {
          "year": 2019,
          "staffPct": 93,
          "freelancePct": 7
        },
        {
          "year": 2020,
          "staffPct": 91,
          "freelancePct": 9
        },
        {
          "year": 2021,
          "staffPct": 90,
          "freelancePct": 10
        },
        {
          "year": 2022,
          "staffPct": 89,
          "freelancePct": 11
        },
        {
          "year": 2023,
          "staffPct": 87,
          "freelancePct": 13
        },
        {
          "year": 2024,
          "staffPct": 86,
          "freelancePct": 14
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 86,
        "freelancePct": 14
      },
      "wageGap": {
        "staffMedianUSD": 225000,
        "freelanceMedianUSD": 185000,
        "gapPct": 17.8
      },
      "reportYear": 2024
    }
  },
  "senior-product-designer": {
    "slug": "senior-product-designer",
    "acs": null,
    "nea": {
      "blsCount": 112400,
      "moonlightingCount": 191100,
      "trueSupplyCount": 303500,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 80,
          "freelancePct": 20
        },
        {
          "year": 2019,
          "staffPct": 78,
          "freelancePct": 22
        },
        {
          "year": 2020,
          "staffPct": 73,
          "freelancePct": 27
        },
        {
          "year": 2021,
          "staffPct": 70,
          "freelancePct": 30
        },
        {
          "year": 2022,
          "staffPct": 67,
          "freelancePct": 33
        },
        {
          "year": 2023,
          "staffPct": 64,
          "freelancePct": 36
        },
        {
          "year": 2024,
          "staffPct": 62,
          "freelancePct": 38
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 62,
        "freelancePct": 38
      },
      "wageGap": {
        "staffMedianUSD": 145000,
        "freelanceMedianUSD": 110000,
        "gapPct": 24.1
      },
      "reportYear": 2024
    }
  },
  "ux-designer": {
    "slug": "ux-designer",
    "acs": null,
    "nea": {
      "blsCount": 134800,
      "moonlightingCount": 229200,
      "trueSupplyCount": 364000,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 76,
          "freelancePct": 24
        },
        {
          "year": 2019,
          "staffPct": 74,
          "freelancePct": 26
        },
        {
          "year": 2020,
          "staffPct": 69,
          "freelancePct": 31
        },
        {
          "year": 2021,
          "staffPct": 66,
          "freelancePct": 34
        },
        {
          "year": 2022,
          "staffPct": 63,
          "freelancePct": 37
        },
        {
          "year": 2023,
          "staffPct": 60,
          "freelancePct": 40
        },
        {
          "year": 2024,
          "staffPct": 58,
          "freelancePct": 42
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 58,
        "freelancePct": 42
      },
      "wageGap": {
        "staffMedianUSD": 115000,
        "freelanceMedianUSD": 82000,
        "gapPct": 28.7
      },
      "reportYear": 2024
    }
  },
  "product-designer": {
    "slug": "product-designer",
    "acs": null,
    "nea": {
      "blsCount": 98700,
      "moonlightingCount": 167800,
      "trueSupplyCount": 266500,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 77,
          "freelancePct": 23
        },
        {
          "year": 2019,
          "staffPct": 75,
          "freelancePct": 25
        },
        {
          "year": 2020,
          "staffPct": 70,
          "freelancePct": 30
        },
        {
          "year": 2021,
          "staffPct": 67,
          "freelancePct": 33
        },
        {
          "year": 2022,
          "staffPct": 64,
          "freelancePct": 36
        },
        {
          "year": 2023,
          "staffPct": 61,
          "freelancePct": 39
        },
        {
          "year": 2024,
          "staffPct": 59,
          "freelancePct": 41
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 59,
        "freelancePct": 41
      },
      "wageGap": {
        "staffMedianUSD": 125000,
        "freelanceMedianUSD": 90000,
        "gapPct": 28
      },
      "reportYear": 2024
    }
  },
  "ux-researcher": {
    "slug": "ux-researcher",
    "acs": null,
    "nea": {
      "blsCount": 41200,
      "moonlightingCount": 70000,
      "trueSupplyCount": 111200,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 84,
          "freelancePct": 16
        },
        {
          "year": 2019,
          "staffPct": 82,
          "freelancePct": 18
        },
        {
          "year": 2020,
          "staffPct": 78,
          "freelancePct": 22
        },
        {
          "year": 2021,
          "staffPct": 75,
          "freelancePct": 25
        },
        {
          "year": 2022,
          "staffPct": 72,
          "freelancePct": 28
        },
        {
          "year": 2023,
          "staffPct": 69,
          "freelancePct": 31
        },
        {
          "year": 2024,
          "staffPct": 67,
          "freelancePct": 33
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 67,
        "freelancePct": 33
      },
      "wageGap": {
        "staffMedianUSD": 120000,
        "freelanceMedianUSD": 92000,
        "gapPct": 23.3
      },
      "reportYear": 2024
    }
  },
  "design-systems-designer": {
    "slug": "design-systems-designer",
    "acs": null,
    "nea": {
      "blsCount": 22600,
      "moonlightingCount": 38400,
      "trueSupplyCount": 61000,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 86,
          "freelancePct": 14
        },
        {
          "year": 2019,
          "staffPct": 84,
          "freelancePct": 16
        },
        {
          "year": 2020,
          "staffPct": 80,
          "freelancePct": 20
        },
        {
          "year": 2021,
          "staffPct": 77,
          "freelancePct": 23
        },
        {
          "year": 2022,
          "staffPct": 74,
          "freelancePct": 26
        },
        {
          "year": 2023,
          "staffPct": 71,
          "freelancePct": 29
        },
        {
          "year": 2024,
          "staffPct": 69,
          "freelancePct": 31
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 69,
        "freelancePct": 31
      },
      "wageGap": {
        "staffMedianUSD": 140000,
        "freelanceMedianUSD": 108000,
        "gapPct": 22.9
      },
      "reportYear": 2024
    }
  },
  "brand-designer": {
    "slug": "brand-designer",
    "acs": null,
    "nea": {
      "blsCount": 67400,
      "moonlightingCount": 114600,
      "trueSupplyCount": 182000,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 70,
          "freelancePct": 30
        },
        {
          "year": 2019,
          "staffPct": 68,
          "freelancePct": 32
        },
        {
          "year": 2020,
          "staffPct": 63,
          "freelancePct": 37
        },
        {
          "year": 2021,
          "staffPct": 60,
          "freelancePct": 40
        },
        {
          "year": 2022,
          "staffPct": 57,
          "freelancePct": 43
        },
        {
          "year": 2023,
          "staffPct": 54,
          "freelancePct": 46
        },
        {
          "year": 2024,
          "staffPct": 52,
          "freelancePct": 48
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 52,
        "freelancePct": 48
      },
      "wageGap": {
        "staffMedianUSD": 85000,
        "freelanceMedianUSD": 62000,
        "gapPct": 27.1
      },
      "reportYear": 2024
    }
  },
  "graphic-designer": {
    "slug": "graphic-designer",
    "acs": null,
    "nea": {
      "blsCount": 254800,
      "moonlightingCount": 433200,
      "trueSupplyCount": 688000,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 65,
          "freelancePct": 35
        },
        {
          "year": 2019,
          "staffPct": 63,
          "freelancePct": 37
        },
        {
          "year": 2020,
          "staffPct": 58,
          "freelancePct": 42
        },
        {
          "year": 2021,
          "staffPct": 55,
          "freelancePct": 45
        },
        {
          "year": 2022,
          "staffPct": 52,
          "freelancePct": 48
        },
        {
          "year": 2023,
          "staffPct": 49,
          "freelancePct": 51
        },
        {
          "year": 2024,
          "staffPct": 47,
          "freelancePct": 53
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 47,
        "freelancePct": 53
      },
      "wageGap": {
        "staffMedianUSD": 58000,
        "freelanceMedianUSD": 42000,
        "gapPct": 27.6
      },
      "reportYear": 2024
    }
  },
  "visual-designer": {
    "slug": "visual-designer",
    "acs": null,
    "nea": {
      "blsCount": 78300,
      "moonlightingCount": 133100,
      "trueSupplyCount": 211400,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 72,
          "freelancePct": 28
        },
        {
          "year": 2019,
          "staffPct": 70,
          "freelancePct": 30
        },
        {
          "year": 2020,
          "staffPct": 65,
          "freelancePct": 35
        },
        {
          "year": 2021,
          "staffPct": 62,
          "freelancePct": 38
        },
        {
          "year": 2022,
          "staffPct": 59,
          "freelancePct": 41
        },
        {
          "year": 2023,
          "staffPct": 56,
          "freelancePct": 44
        },
        {
          "year": 2024,
          "staffPct": 54,
          "freelancePct": 46
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 54,
        "freelancePct": 46
      },
      "wageGap": {
        "staffMedianUSD": 92000,
        "freelanceMedianUSD": 68000,
        "gapPct": 26.1
      },
      "reportYear": 2024
    }
  },
  "art-director": {
    "slug": "art-director",
    "acs": null,
    "nea": {
      "blsCount": 97600,
      "moonlightingCount": 165900,
      "trueSupplyCount": 263500,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 75,
          "freelancePct": 25
        },
        {
          "year": 2019,
          "staffPct": 73,
          "freelancePct": 27
        },
        {
          "year": 2020,
          "staffPct": 68,
          "freelancePct": 32
        },
        {
          "year": 2021,
          "staffPct": 65,
          "freelancePct": 35
        },
        {
          "year": 2022,
          "staffPct": 63,
          "freelancePct": 37
        },
        {
          "year": 2023,
          "staffPct": 60,
          "freelancePct": 40
        },
        {
          "year": 2024,
          "staffPct": 58,
          "freelancePct": 42
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 58,
        "freelancePct": 42
      },
      "wageGap": {
        "staffMedianUSD": 110000,
        "freelanceMedianUSD": 82000,
        "gapPct": 25.5
      },
      "reportYear": 2024
    }
  },
  "motion-designer": {
    "slug": "motion-designer",
    "acs": null,
    "nea": {
      "blsCount": 87200,
      "moonlightingCount": 148200,
      "trueSupplyCount": 235400,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 62,
          "freelancePct": 38
        },
        {
          "year": 2019,
          "staffPct": 60,
          "freelancePct": 40
        },
        {
          "year": 2020,
          "staffPct": 55,
          "freelancePct": 45
        },
        {
          "year": 2021,
          "staffPct": 52,
          "freelancePct": 48
        },
        {
          "year": 2022,
          "staffPct": 49,
          "freelancePct": 51
        },
        {
          "year": 2023,
          "staffPct": 46,
          "freelancePct": 54
        },
        {
          "year": 2024,
          "staffPct": 44,
          "freelancePct": 56
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 44,
        "freelancePct": 56
      },
      "wageGap": {
        "staffMedianUSD": 95000,
        "freelanceMedianUSD": 72000,
        "gapPct": 24.2
      },
      "reportYear": 2024
    }
  },
  "copywriter": {
    "slug": "copywriter",
    "acs": null,
    "nea": {
      "blsCount": 143200,
      "moonlightingCount": 243400,
      "trueSupplyCount": 386600,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 60,
          "freelancePct": 40
        },
        {
          "year": 2019,
          "staffPct": 58,
          "freelancePct": 42
        },
        {
          "year": 2020,
          "staffPct": 53,
          "freelancePct": 47
        },
        {
          "year": 2021,
          "staffPct": 50,
          "freelancePct": 50
        },
        {
          "year": 2022,
          "staffPct": 47,
          "freelancePct": 53
        },
        {
          "year": 2023,
          "staffPct": 44,
          "freelancePct": 56
        },
        {
          "year": 2024,
          "staffPct": 42,
          "freelancePct": 58
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 42,
        "freelancePct": 58
      },
      "wageGap": {
        "staffMedianUSD": 72000,
        "freelanceMedianUSD": 48000,
        "gapPct": 33.3
      },
      "reportYear": 2024
    }
  },
  "content-strategist": {
    "slug": "content-strategist",
    "acs": null,
    "nea": {
      "blsCount": 52800,
      "moonlightingCount": 89800,
      "trueSupplyCount": 142600,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 74,
          "freelancePct": 26
        },
        {
          "year": 2019,
          "staffPct": 72,
          "freelancePct": 28
        },
        {
          "year": 2020,
          "staffPct": 67,
          "freelancePct": 33
        },
        {
          "year": 2021,
          "staffPct": 64,
          "freelancePct": 36
        },
        {
          "year": 2022,
          "staffPct": 61,
          "freelancePct": 39
        },
        {
          "year": 2023,
          "staffPct": 58,
          "freelancePct": 42
        },
        {
          "year": 2024,
          "staffPct": 56,
          "freelancePct": 44
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 56,
        "freelancePct": 44
      },
      "wageGap": {
        "staffMedianUSD": 98000,
        "freelanceMedianUSD": 72000,
        "gapPct": 26.5
      },
      "reportYear": 2024
    }
  },
  "ux-writer": {
    "slug": "ux-writer",
    "acs": null,
    "nea": {
      "blsCount": 31400,
      "moonlightingCount": 53400,
      "trueSupplyCount": 84800,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 80,
          "freelancePct": 20
        },
        {
          "year": 2019,
          "staffPct": 78,
          "freelancePct": 22
        },
        {
          "year": 2020,
          "staffPct": 73,
          "freelancePct": 27
        },
        {
          "year": 2021,
          "staffPct": 70,
          "freelancePct": 30
        },
        {
          "year": 2022,
          "staffPct": 67,
          "freelancePct": 33
        },
        {
          "year": 2023,
          "staffPct": 64,
          "freelancePct": 36
        },
        {
          "year": 2024,
          "staffPct": 62,
          "freelancePct": 38
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 62,
        "freelancePct": 38
      },
      "wageGap": {
        "staffMedianUSD": 108000,
        "freelanceMedianUSD": 78000,
        "gapPct": 27.8
      },
      "reportYear": 2024
    }
  },
  "creative-copywriter": {
    "slug": "creative-copywriter",
    "acs": null,
    "nea": {
      "blsCount": 68900,
      "moonlightingCount": 117100,
      "trueSupplyCount": 186000,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 64,
          "freelancePct": 36
        },
        {
          "year": 2019,
          "staffPct": 62,
          "freelancePct": 38
        },
        {
          "year": 2020,
          "staffPct": 57,
          "freelancePct": 43
        },
        {
          "year": 2021,
          "staffPct": 54,
          "freelancePct": 46
        },
        {
          "year": 2022,
          "staffPct": 51,
          "freelancePct": 49
        },
        {
          "year": 2023,
          "staffPct": 48,
          "freelancePct": 52
        },
        {
          "year": 2024,
          "staffPct": 46,
          "freelancePct": 54
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 46,
        "freelancePct": 54
      },
      "wageGap": {
        "staffMedianUSD": 82000,
        "freelanceMedianUSD": 58000,
        "gapPct": 29.3
      },
      "reportYear": 2024
    }
  },
  "content-designer": {
    "slug": "content-designer",
    "acs": null,
    "nea": {
      "blsCount": 38600,
      "moonlightingCount": 65600,
      "trueSupplyCount": 104200,
      "supplyMultiplier": 2.7,
      "moonlightingSharePct": 63,
      "reportYear": 2024
    },
    "upwork": {
      "splitTrend": [
        {
          "year": 2018,
          "staffPct": 78,
          "freelancePct": 22
        },
        {
          "year": 2019,
          "staffPct": 76,
          "freelancePct": 24
        },
        {
          "year": 2020,
          "staffPct": 71,
          "freelancePct": 29
        },
        {
          "year": 2021,
          "staffPct": 68,
          "freelancePct": 32
        },
        {
          "year": 2022,
          "staffPct": 65,
          "freelancePct": 35
        },
        {
          "year": 2023,
          "staffPct": 62,
          "freelancePct": 38
        },
        {
          "year": 2024,
          "staffPct": 60,
          "freelancePct": 40
        }
      ],
      "currentSplit": {
        "year": 2024,
        "staffPct": 60,
        "freelancePct": 40
      },
      "wageGap": {
        "staffMedianUSD": 105000,
        "freelanceMedianUSD": 76000,
        "gapPct": 27.6
      },
      "reportYear": 2024
    }
  }
};

export const CACHED_MARKET_ENRICHMENT: MarketEnrichment | null = {
  "fred": null,
  "aggregateNEA": {
    "totalBLSCount": 1521500,
    "totalTrueSupply": 4107000,
    "overallMultiplier": 2.7
  },
  "aggregateUpwork": {
    "avgFreelancePct": 39.6,
    "splitTrend": [
      {
        "year": 2018,
        "staffPct": 74,
        "freelancePct": 26
      },
      {
        "year": 2019,
        "staffPct": 72,
        "freelancePct": 28
      },
      {
        "year": 2020,
        "staffPct": 66,
        "freelancePct": 34
      },
      {
        "year": 2021,
        "staffPct": 63,
        "freelancePct": 37
      },
      {
        "year": 2022,
        "staffPct": 61,
        "freelancePct": 39
      },
      {
        "year": 2023,
        "staffPct": 58,
        "freelancePct": 42
      },
      {
        "year": 2024,
        "staffPct": 56,
        "freelancePct": 44
      }
    ]
  },
  "generatedAt": "2026-03-12T13:19:22.498Z"
};
