// Auto-generated — do not edit manually.
// Regenerated by the weekly refresh script alongside role snapshots.
// Generated: 2026-03-11T13:19:48.833Z

import type { RoleSummary } from "./landingData";

export const CACHED_ROLE_SUMMARIES: RoleSummary[] = [
  {
    "title": "Creative Director",
    "slug": "creative-director",
    "cluster": "design-leadership",
    "openingsCount": 2830,
    "yoyChange": -33.3,
    "medianSalary": 128100,
    "aiScore": 27,
    "aiLabel": "Moderate",
    "sparkline": [
      71,
      60,
      62,
      88,
      76,
      54
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Design Director",
    "slug": "design-director",
    "cluster": "design-leadership",
    "openingsCount": 6707,
    "yoyChange": 11.8,
    "medianSalary": 128100,
    "aiScore": 26,
    "aiLabel": "Moderate",
    "sparkline": [
      47,
      42,
      54,
      80,
      72,
      38
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Head of Design",
    "slug": "head-of-design",
    "cluster": "design-leadership",
    "openingsCount": 1211,
    "yoyChange": 0,
    "medianSalary": 0,
    "aiScore": 16,
    "aiLabel": "Low",
    "sparkline": [
      0,
      0,
      17,
      63,
      57,
      8
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "VP of Design",
    "slug": "vp-of-design",
    "cluster": "design-leadership",
    "openingsCount": 403,
    "yoyChange": 0,
    "medianSalary": 0,
    "aiScore": 13,
    "aiLabel": "Low",
    "sparkline": [
      0,
      0,
      0,
      0,
      2,
      5
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Chief Creative Officer",
    "slug": "cco",
    "cluster": "design-leadership",
    "openingsCount": 57,
    "yoyChange": 0,
    "medianSalary": 0,
    "aiScore": 7,
    "aiLabel": "Low",
    "sparkline": [
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Senior Product Designer",
    "slug": "senior-product-designer",
    "cluster": "product-ux",
    "openingsCount": 1251,
    "yoyChange": 12.4,
    "medianSalary": 88000,
    "aiScore": 36,
    "aiLabel": "Moderate",
    "sparkline": [
      0,
      0,
      0,
      0,
      25,
      9
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "UX Designer",
    "slug": "ux-designer",
    "cluster": "product-ux",
    "openingsCount": 12614,
    "yoyChange": -44.4,
    "medianSalary": 111450,
    "aiScore": 36,
    "aiLabel": "Moderate",
    "sparkline": [
      18,
      13,
      15,
      21,
      16,
      10
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Product Designer",
    "slug": "product-designer",
    "cluster": "product-ux",
    "openingsCount": 98721,
    "yoyChange": -17.6,
    "medianSalary": 88000,
    "aiScore": 40,
    "aiLabel": "Moderate",
    "sparkline": [
      45,
      62,
      63,
      83,
      69,
      42
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "UX Researcher",
    "slug": "ux-researcher",
    "cluster": "product-ux",
    "openingsCount": 2729,
    "yoyChange": 8.3,
    "medianSalary": 73470,
    "aiScore": 29,
    "aiLabel": "Moderate",
    "sparkline": [
      24,
      19,
      20,
      28,
      38,
      26
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Design Systems Designer",
    "slug": "design-systems-designer",
    "cluster": "product-ux",
    "openingsCount": 11470,
    "yoyChange": 0,
    "medianSalary": 111450,
    "aiScore": 39,
    "aiLabel": "Moderate",
    "sparkline": [
      0,
      0,
      0,
      0,
      25,
      50
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Brand Designer",
    "slug": "brand-designer",
    "cluster": "brand-visual",
    "openingsCount": 11341,
    "yoyChange": 0,
    "medianSalary": 68610,
    "aiScore": 61,
    "aiLabel": "Elevated",
    "sparkline": [
      11,
      38,
      51,
      76,
      59,
      29
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Graphic Designer",
    "slug": "graphic-designer",
    "cluster": "brand-visual",
    "openingsCount": 13038,
    "yoyChange": -30.1,
    "medianSalary": 68610,
    "aiScore": 69,
    "aiLabel": "Elevated",
    "sparkline": [
      62,
      57,
      48,
      73,
      60,
      58
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Visual Designer",
    "slug": "visual-designer",
    "cluster": "brand-visual",
    "openingsCount": 13352,
    "yoyChange": 0,
    "medianSalary": 68610,
    "aiScore": 66,
    "aiLabel": "Elevated",
    "sparkline": [
      0,
      0,
      0,
      39,
      39,
      15
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Art Director",
    "slug": "art-director",
    "cluster": "brand-visual",
    "openingsCount": 1907,
    "yoyChange": -37.8,
    "medianSalary": 128100,
    "aiScore": 38,
    "aiLabel": "Moderate",
    "sparkline": [
      54,
      52,
      57,
      77,
      74,
      46
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Motion Designer",
    "slug": "motion-designer",
    "cluster": "brand-visual",
    "openingsCount": 2661,
    "yoyChange": 0,
    "medianSalary": 110110,
    "aiScore": 46,
    "aiLabel": "Moderate",
    "sparkline": [
      0,
      0,
      0,
      42,
      6,
      16
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Copywriter",
    "slug": "copywriter",
    "cluster": "content-copy",
    "openingsCount": 3866,
    "yoyChange": -36.8,
    "medianSalary": 85780,
    "aiScore": 76,
    "aiLabel": "High",
    "sparkline": [
      55,
      58,
      43,
      60,
      52,
      48
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Content Strategist",
    "slug": "content-strategist",
    "cluster": "content-copy",
    "openingsCount": 1203,
    "yoyChange": 0,
    "medianSalary": 85780,
    "aiScore": 48,
    "aiLabel": "Moderate",
    "sparkline": [
      0,
      0,
      0,
      25,
      32,
      42
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "UX Writer",
    "slug": "ux-writer",
    "cluster": "content-copy",
    "openingsCount": 169,
    "yoyChange": -50,
    "medianSalary": 85780,
    "aiScore": 62,
    "aiLabel": "Elevated",
    "sparkline": [
      0,
      11,
      0,
      17,
      2,
      7
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Creative Copywriter",
    "slug": "creative-copywriter",
    "cluster": "content-copy",
    "openingsCount": 699,
    "yoyChange": 0,
    "medianSalary": 85780,
    "aiScore": 66,
    "aiLabel": "Elevated",
    "sparkline": [
      0,
      0,
      0,
      0,
      2,
      5
    ],
    "lastUpdated": "2026-03-09"
  },
  {
    "title": "Content Designer",
    "slug": "content-designer",
    "cluster": "content-copy",
    "openingsCount": 10235,
    "yoyChange": 0,
    "medianSalary": 111450,
    "aiScore": 36,
    "aiLabel": "Moderate",
    "sparkline": [
      0,
      33,
      34,
      42,
      40,
      14
    ],
    "lastUpdated": "2026-03-09"
  }
];

export const CACHE_TIMESTAMP = "2026-03-11T13:19:48.833Z";
