// Auto-generated — do not edit manually.
// Regenerated by the weekly refresh script alongside role snapshots.
// Generated: 2026-03-12T13:19:22.465Z

import type { RoleSummary } from "./landingData";

export const CACHED_ROLE_SUMMARIES: RoleSummary[] = [
  {
    "title": "Creative Director",
    "slug": "creative-director",
    "cluster": "design-leadership",
    "openingsCount": 2898,
    "yoyChange": -26.7,
    "medianSalary": 128100,
    "aiScore": 19,
    "aiLabel": "Low",
    "sparkline": [
      72,
      60,
      61,
      88,
      83,
      63
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Design Director",
    "slug": "design-director",
    "cluster": "design-leadership",
    "openingsCount": 6671,
    "yoyChange": 26.7,
    "medianSalary": 128100,
    "aiScore": 18,
    "aiLabel": "Low",
    "sparkline": [
      42,
      34,
      48,
      73,
      83,
      38
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Head of Design",
    "slug": "head-of-design",
    "cluster": "design-leadership",
    "openingsCount": 1234,
    "yoyChange": 0,
    "medianSalary": 0,
    "aiScore": 16,
    "aiLabel": "Low",
    "sparkline": [
      0,
      15,
      55,
      65,
      60,
      29
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "VP of Design",
    "slug": "vp-of-design",
    "cluster": "design-leadership",
    "openingsCount": 396,
    "yoyChange": 0,
    "medianSalary": 0,
    "aiScore": 13,
    "aiLabel": "Low",
    "sparkline": [
      0,
      0,
      0,
      0,
      0,
      50
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Chief Creative Officer",
    "slug": "cco",
    "cluster": "design-leadership",
    "openingsCount": 58,
    "yoyChange": 0,
    "medianSalary": 0,
    "aiScore": 7,
    "aiLabel": "Low",
    "sparkline": [
      0,
      0,
      0,
      24,
      0,
      0
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Senior Product Designer",
    "slug": "senior-product-designer",
    "cluster": "product-ux",
    "openingsCount": 1265,
    "yoyChange": 12.4,
    "medianSalary": 88000,
    "aiScore": 36,
    "aiLabel": "Moderate",
    "sparkline": [
      0,
      0,
      0,
      0,
      10,
      93
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "UX Designer",
    "slug": "ux-designer",
    "cluster": "product-ux",
    "openingsCount": 12547,
    "yoyChange": -35.3,
    "medianSalary": 111450,
    "aiScore": 35,
    "aiLabel": "Moderate",
    "sparkline": [
      20,
      12,
      14,
      21,
      15,
      11
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Product Designer",
    "slug": "product-designer",
    "cluster": "product-ux",
    "openingsCount": 97332,
    "yoyChange": -5.8,
    "medianSalary": 88000,
    "aiScore": 40,
    "aiLabel": "Moderate",
    "sparkline": [
      45,
      61,
      61,
      92,
      66,
      49
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "UX Researcher",
    "slug": "ux-researcher",
    "cluster": "product-ux",
    "openingsCount": 2667,
    "yoyChange": 41.7,
    "medianSalary": 73470,
    "aiScore": 27,
    "aiLabel": "Moderate",
    "sparkline": [
      24,
      18,
      13,
      27,
      38,
      34
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Design Systems Designer",
    "slug": "design-systems-designer",
    "cluster": "product-ux",
    "openingsCount": 11352,
    "yoyChange": 0,
    "medianSalary": 111450,
    "aiScore": 38,
    "aiLabel": "Moderate",
    "sparkline": [
      0,
      0,
      0,
      0,
      0,
      50
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Brand Designer",
    "slug": "brand-designer",
    "cluster": "brand-visual",
    "openingsCount": 11232,
    "yoyChange": 0,
    "medianSalary": 68610,
    "aiScore": 59,
    "aiLabel": "Elevated",
    "sparkline": [
      0,
      60,
      68,
      88,
      82,
      48
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Graphic Designer",
    "slug": "graphic-designer",
    "cluster": "brand-visual",
    "openingsCount": 12823,
    "yoyChange": -26.1,
    "medianSalary": 68610,
    "aiScore": 67,
    "aiLabel": "Elevated",
    "sparkline": [
      64,
      61,
      50,
      77,
      69,
      65
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Visual Designer",
    "slug": "visual-designer",
    "cluster": "brand-visual",
    "openingsCount": 13307,
    "yoyChange": 161.5,
    "medianSalary": 68610,
    "aiScore": 64,
    "aiLabel": "Elevated",
    "sparkline": [
      15,
      0,
      0,
      17,
      25,
      34
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Art Director",
    "slug": "art-director",
    "cluster": "brand-visual",
    "openingsCount": 1966,
    "yoyChange": -23.6,
    "medianSalary": 128100,
    "aiScore": 30,
    "aiLabel": "Moderate",
    "sparkline": [
      59,
      55,
      59,
      76,
      86,
      55
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Motion Designer",
    "slug": "motion-designer",
    "cluster": "brand-visual",
    "openingsCount": 2761,
    "yoyChange": 0,
    "medianSalary": 110110,
    "aiScore": 46,
    "aiLabel": "Moderate",
    "sparkline": [
      23,
      0,
      0,
      25,
      3,
      42
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Copywriter",
    "slug": "copywriter",
    "cluster": "content-copy",
    "openingsCount": 3844,
    "yoyChange": -42.3,
    "medianSalary": 85780,
    "aiScore": 69,
    "aiLabel": "Elevated",
    "sparkline": [
      51,
      52,
      42,
      58,
      53,
      45
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Content Strategist",
    "slug": "content-strategist",
    "cluster": "content-copy",
    "openingsCount": 1094,
    "yoyChange": 0,
    "medianSalary": 85780,
    "aiScore": 41,
    "aiLabel": "Moderate",
    "sparkline": [
      0,
      0,
      0,
      0,
      16,
      24
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "UX Writer",
    "slug": "ux-writer",
    "cluster": "content-copy",
    "openingsCount": 164,
    "yoyChange": 0,
    "medianSalary": 85780,
    "aiScore": 55,
    "aiLabel": "Elevated",
    "sparkline": [
      0,
      0,
      0,
      0,
      1,
      10
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Creative Copywriter",
    "slug": "creative-copywriter",
    "cluster": "content-copy",
    "openingsCount": 694,
    "yoyChange": 0,
    "medianSalary": 85780,
    "aiScore": 59,
    "aiLabel": "Elevated",
    "sparkline": [
      0,
      0,
      0,
      0,
      0,
      15
    ],
    "lastUpdated": "2026-03-12"
  },
  {
    "title": "Content Designer",
    "slug": "content-designer",
    "cluster": "content-copy",
    "openingsCount": 10049,
    "yoyChange": 0,
    "medianSalary": 111450,
    "aiScore": 35,
    "aiLabel": "Moderate",
    "sparkline": [
      0,
      13,
      33,
      43,
      42,
      28
    ],
    "lastUpdated": "2026-03-12"
  }
];

export const CACHE_TIMESTAMP = "2026-03-12T13:19:22.465Z";
